version: "3.9"

services:
    bot:
      container_name: uncle
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
        target: base
      ports:
        - 3000:3000
